name: PythonCiCd

on:
  workflows: ["OnInstall"]
    branches: [ "main" ]
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: lint
        run: make lint
