name: Test

on:
  workflow_run:
    workflows: ["OnInstall"]
    branches: ["main"]
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install ruff
      - run: pip install nbqa
      - name: lint
        run: make lint
